#!/bin/bash

if [ $# -ne 1 ]
then 
  exit 1
fi
  if ! [ -d $(~/.trash) ]
 then
  mkdir $(~/.trash)
  fi
data=$(date "+%d-%m-%Y_%H-%M-%S")
  ln $1 "(~/.trash)/$(~/trash.log)"
  rm $1
 if ! [ -e $(~/trash.log) ]
  then
 touch $(~/trash.log)
 fi
  echo "$PWD/$1:$data" >> /trash.log
