#!/bin/bash

cd $HOME/.trash.log
 for file in *;
do
  if [[ "$file" == *"$1"* ]]; then
 echo "Yes/No?"
 echo "$file"
read answer
 case $answer in
"No")
break
;;
"Yes")
file_name=$(echo $file | awk -F ":" '{print $1}')
link_file=$(echo $file | awk -F ":" '{print $2}')
  if [[ -e $file ]] ; then
 read n
  ln "$trash/$link_file" "$(/home/user/AllLabs_OS)/$n"
 else
  ln "$trash/$link_file" "$file_name"
  fi
break
;;
*)
exit 1
;;
esac
  fi
rm "$trash/$link_file"
 # sed -i
done
